In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("Hello, TensorFlow!")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a, b, c]))

sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


In [7]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)


In [8]:
X_data = [[1, 2, 3], [4, 5, 6]]

In [9]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [11]:
expr = tf.matmul(X, W) + b

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== X_data ===")
print(X_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: X_data}))

sess.close()

=== X_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.03383105  1.07214856]
 [ 0.07707079 -1.28858948]
 [ 1.83965147 -0.69336772]]
=== b ===
[[ 0.45116434]
 [-0.57912886]]
=== expr ===
[[  6.15809107  -3.13396931]
 [ 10.97945786  -6.8936882 ]]


### Linear Regression

In [16]:
X_data = [1, 2, 3]
y_data = [1, 2, 3]

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0)) # shape, range_start, range_end
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name="X")
y = tf.placeholder(tf.float32, name="y")

hypothesis = W * X + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - y)) # Root Mean Square

# Optimization (Gradient Descent)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [20]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: X_data, 
                                                            y: y_data})
#         print(step, cost_val, sess.run(W), sess.run(b))
        
    print("X: 5, y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, y:", sess.run(hypothesis, feed_dict={X: 2.5}))

X: 5, y: [ 4.90281487]
X: 2.5, y: [ 2.49191761]
